# https://stackoverflow.com/questions/63003669/how-can-i-see-my-git-secrets-unencrypted
name: show me the s3cr3tz
on:
  push:
    branches:
      - master

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

        run: |
          echo $TAURI_PRIVATE_KEY >> TAURI_PRIVATE_KEY.txt
          echo $TAURI_KEY_PASSWORD >> TAURI_KEY_PASSWORD.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
